require "pry"
require "open-uri"
require "net/http"
require "json"
require "awesome_print"

require_relative "../lib/modules/recipe_finder"
require_relative "../lib/api"
require_relative "../lib/cli"
require_relative "../lib/recipe"